---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kv-csi-driver
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts

